stages:
  split:
    cmd: python3 code/src/split.py data/src/sales_train.csv
    deps:
      - code/src/split.py
      - data/src/
      - data/src/sales_train.csv
    params:
      - split.train_start_date
      - split.train_end_date
      - split.val_end_date
    outs:
      - data/train/
      - data/val/
  generate_features:
    cmd: python3 code/src/generate_features.py data/train data/val data/src
    deps:
      - code/src/generate_features.py
      - data/src/
      - data/train/
      - data/val/
    outs:
      - data/prepared/train/
      - data/prepared/val/
      - data/prepared/test/
  train:
    cmd: python3 code/src/train.py data/prepared/train
    params:
      - train
    deps:
      - code/src/train.py
      - data/prepared/train/
    outs:
      - model.pkl
  evaluate:
    cmd: python3 code/src/evaluate.py data/prepared/val data/src/

    deps:
      - code/src/evaluate.py
      - data/prepared/val/
      - data/src/
    metrics:
      - metrics.json:
          cache: false
